<?php
/**
 * API Docs metabox fields (Pro Max).
 * Structured editor for the api_docs post type.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$meta = 'ezd_api_docs_meta';

CSF::createMetabox( $meta, array(
	'title'     => esc_html__( 'API Documentation', 'eazydocs' ),
	'post_type' => 'api_docs',
	'data_type' => 'serialize',
	'priority'  => 'high',
	'class'     => 'ezd-api-docs-metabox eazydocs-promax-notice',
) );

CSF::createSection( $meta, array(
	'id'     => 'ezd_api_general',
	'title'  => esc_html__( 'General', 'eazydocs' ),
	'icon'   => 'dashicons dashicons-info-outline',
	'fields' => array(
		array(
			'type'    => 'subheading',
			'content' => esc_html__( 'API Settings', 'eazydocs' ),
		),
		array(
			'type'    => 'notice',
			'style'   => 'info',
			'content' => esc_html__( 'The title above is the public API name. Set the base URL, version, and authentication for this project here.', 'eazydocs' ),
		),
		array(
			'id'       => 'description',
			'type'     => 'wp_editor',
			'title'    => esc_html__( 'Overview', 'eazydocs' ),
			'subtitle' => esc_html__( 'Introductory content shown at the top of the public page, before the first collection.', 'eazydocs' ),
			'default'  => '',
			'sanitize' => 'wp_kses_post',
			'class'    => 'eazydocs-promax-notice',
		),
		array(
			'id'          => 'base_url',
			'type'        => 'text',
			'title'       => esc_html__( 'Base URL', 'eazydocs' ),
			'subtitle'    => esc_html__( 'API root without an endpoint path. Each endpoint path is appended to this URL on the public page.', 'eazydocs' ),
			'placeholder' => 'https://api.example.com/v1',
			'default'     => ezd_get_opt( 'default_base_url', 'https://api.example.com/v1' ),
			'sanitize'    => 'esc_url_raw',
			'class'       => 'eazydocs-promax-notice',
		),
		array(
			'id'          => 'version',
			'type'        => 'text',
			'title'       => esc_html__( 'Version', 'eazydocs' ),
			'subtitle'    => esc_html__( 'Version label shown next to the API name, such as v1. It does not change permalinks.', 'eazydocs' ),
			'placeholder' => 'v1',
			'default'     => ezd_get_opt( 'default_api_version', 'v1' ),
			'sanitize'    => 'sanitize_text_field',
			'class'       => 'eazydocs-promax-notice',
		),
		array(
			'id'       => 'authentication',
			'type'     => 'select',
			'title'    => esc_html__( 'Authentication', 'eazydocs' ),
			'subtitle' => esc_html__( 'How callers authenticate. Shown in the overview. Choose None if the API is public.', 'eazydocs' ),
			'options'  => array(
				'none'    => esc_html__( 'None', 'eazydocs' ),
				'api_key' => esc_html__( 'API Key', 'eazydocs' ),
				'bearer'  => esc_html__( 'Bearer Token', 'eazydocs' ),
				'basic'   => esc_html__( 'Basic Auth', 'eazydocs' ),
				'oauth2'  => esc_html__( 'OAuth 2.0', 'eazydocs' ),
				'custom'  => esc_html__( 'Custom', 'eazydocs' ),
			),
			'default'  => ezd_get_opt( 'default_auth', 'none' ),
			'chosen'   => true,
			'class'    => 'eazydocs-promax-notice',
		),
		array(
			'id'          => 'auth_details',
			'type'        => 'textarea',
			'title'       => esc_html__( 'How to Authenticate', 'eazydocs' ),
			'subtitle'    => esc_html__( 'Tell readers how to send credentials, including the header name and format.', 'eazydocs' ),
			'placeholder' => esc_html__( 'Send your API key in the Authorization header as Bearer YOUR_KEY.', 'eazydocs' ),
			'default'     => '',
			'sanitize'    => 'sanitize_textarea_field',
			'dependency'  => array( 'authentication', '!=', 'none' ),
			'class'       => 'eazydocs-promax-notice',
		),
	),
) );

CSF::createSection( $meta, array(
	'id'     => 'ezd_api_collections',
	'title'  => esc_html__( 'Collections', 'eazydocs' ),
	'icon'   => 'dashicons dashicons-category',
	'fields' => array(
		array(
			'type'    => 'notice',
			'style'   => 'info',
			'content' => esc_html__( 'Group related endpoints into collections, such as Users or Webhooks. Drag to reorder, then expand a collection to add endpoints.', 'eazydocs' ),
		),
		array(
			'id'                     => 'collections',
			'type'                   => 'group',
			'title'                  => esc_html__( 'Collections', 'eazydocs' ),
			'subtitle'               => esc_html__( 'Each collection becomes a section in the left navigation.', 'eazydocs' ),
			'button_title'           => esc_html__( 'Add Collection', 'eazydocs' ),
			'accordion_title_number' => true,
			'accordion_title_by'     => array( 'title', 'slug' ),
			'default'                => array(),
			'sanitize'               => 'ezd_sanitize_api_docs_collections',
			'class'                  => 'eazydocs-promax-notice',
			'fields'                 => array(
				array(
					'id'          => 'title',
					'type'        => 'text',
					'title'       => esc_html__( 'Name', 'eazydocs' ),
					'subtitle'    => esc_html__( 'Sidebar heading for this group of endpoints, such as Users.', 'eazydocs' ),
					'placeholder' => esc_html__( 'Users', 'eazydocs' ),
					'default'     => '',
				),
				array(
					'id'          => 'slug',
					'type'        => 'text',
					'title'       => esc_html__( 'Slug', 'eazydocs' ),
					'subtitle'    => esc_html__( 'Optional URL-safe ID used for in-page links. Leave blank to generate it from the name.', 'eazydocs' ),
					'placeholder' => 'users',
					'default'     => '',
				),
				array(
					'id'         => 'enabled',
					'type'       => 'switcher',
					'title'      => esc_html__( 'Visible', 'eazydocs' ),
					'subtitle'   => esc_html__( 'Hide this collection from the public page without deleting it.', 'eazydocs' ),
					'text_on'    => esc_html__( 'Show', 'eazydocs' ),
					'text_off'   => esc_html__( 'Hide', 'eazydocs' ),
					'text_width' => 80,
					'default'    => true,
				),
				array(
					'id'                     => 'endpoints',
					'type'                   => 'group',
					'title'                  => esc_html__( 'Endpoints', 'eazydocs' ),
					'subtitle'               => esc_html__( 'Each item is one HTTP operation. Drag to reorder them within this collection.', 'eazydocs' ),
					'button_title'           => esc_html__( 'Add Endpoint', 'eazydocs' ),
					'accordion_title_number' => true,
					'accordion_title_by'     => array( 'method', 'path', 'title' ),
					'default'                => array(),
					'fields'                 => array(
						array(
							'id'          => 'title',
							'type'        => 'text',
							'title'       => esc_html__( 'Name', 'eazydocs' ),
							'subtitle'    => esc_html__( 'Public heading for this operation, such as List users.', 'eazydocs' ),
							'placeholder' => esc_html__( 'List users', 'eazydocs' ),
							'default'     => '',
						),
						array(
							'id'       => 'method',
							'type'     => 'select',
							'title'    => esc_html__( 'Method', 'eazydocs' ),
							'subtitle' => esc_html__( 'HTTP verb for this operation. Shown as a badge beside the path.', 'eazydocs' ),
							'options'  => array(
								'GET'    => 'GET',
								'POST'   => 'POST',
								'PUT'    => 'PUT',
								'PATCH'  => 'PATCH',
								'DELETE' => 'DELETE',
							),
							'default'  => 'GET',
						),
						array(
							'id'          => 'path',
							'type'        => 'text',
							'title'       => esc_html__( 'Path', 'eazydocs' ),
							'subtitle'    => esc_html__( 'Path relative to the Base URL. Use {id} for path variables, such as /users/{id}.', 'eazydocs' ),
							'placeholder' => '/users/{id}',
							'default'     => '',
						),
						array(
							'id'          => 'description',
							'type'        => 'textarea',
							'title'       => esc_html__( 'Description', 'eazydocs' ),
							'subtitle'    => esc_html__( 'Explain what this endpoint does. Shown in the center documentation column.', 'eazydocs' ),
							'placeholder' => esc_html__( 'Returns a paginated list of users.', 'eazydocs' ),
							'default'     => '',
						),
						array(
							'id'    => 'details',
							'type'  => 'tabbed',
							'title' => esc_html__( 'Endpoint Details', 'eazydocs' ),
							'tabs'  => array(
								array(
									'title'  => esc_html__( 'Parameters', 'eazydocs' ),
									'fields' => array(
										array(
											'id'                     => 'parameters',
											'type'                   => 'group',
											'title'                  => esc_html__( 'Parameters', 'eazydocs' ),
											'subtitle'               => esc_html__( 'Query, path, and header inputs. Path names must match {placeholders} in the path.', 'eazydocs' ),
											'button_title'           => esc_html__( 'Add Parameter', 'eazydocs' ),
											'accordion_title_number' => true,
											'accordion_title_by'     => array( 'name', 'in' ),
											'default'                => array(),
											'fields'                 => array(
												array(
													'id'          => 'name',
													'type'        => 'text',
													'title'       => esc_html__( 'Name', 'eazydocs' ),
													'subtitle'    => esc_html__( 'Parameter key sent to the API, such as limit or id.', 'eazydocs' ),
													'placeholder' => 'limit',
													'default'     => '',
												),
												array(
													'id'       => 'in',
													'type'     => 'select',
													'title'    => esc_html__( 'Location', 'eazydocs' ),
													'subtitle' => esc_html__( 'Where this parameter is sent: query string, path, or header.', 'eazydocs' ),
													'options'  => array(
														'query'  => esc_html__( 'Query', 'eazydocs' ),
														'path'   => esc_html__( 'Path', 'eazydocs' ),
														'header' => esc_html__( 'Header', 'eazydocs' ),
													),
													'default'  => 'query',
												),
												array(
													'id'       => 'type',
													'type'     => 'select',
													'title'    => esc_html__( 'Data Type', 'eazydocs' ),
													'subtitle' => esc_html__( 'Expected value type for this parameter.', 'eazydocs' ),
													'options'  => array(
														'string'  => 'string',
														'integer' => 'integer',
														'number'  => 'number',
														'boolean' => 'boolean',
														'array'   => 'array',
														'object'  => 'object',
														'file'    => 'file',
													),
													'default'  => 'string',
												),
												array(
													'id'       => 'required',
													'type'     => 'switcher',
													'title'    => esc_html__( 'Required', 'eazydocs' ),
													'subtitle' => esc_html__( 'Mark as required if the API rejects the request when this parameter is missing.', 'eazydocs' ),
													'text_on'  => esc_html__( 'Yes', 'eazydocs' ),
													'text_off' => esc_html__( 'No', 'eazydocs' ),
													'default'  => false,
												),
												array(
													'id'          => 'default',
													'type'        => 'text',
													'title'       => esc_html__( 'Default Value', 'eazydocs' ),
													'subtitle'    => esc_html__( 'Value the API uses when the parameter is omitted.', 'eazydocs' ),
													'placeholder' => '20',
													'default'     => '',
												),
												array(
													'id'          => 'example',
													'type'        => 'text',
													'title'       => esc_html__( 'Example Value', 'eazydocs' ),
													'subtitle'    => esc_html__( 'Sample value shown in the parameter table on the public page.', 'eazydocs' ),
													'placeholder' => '10',
													'default'     => '',
												),
												array(
													'id'       => 'description',
													'type'     => 'textarea',
													'title'    => esc_html__( 'Description', 'eazydocs' ),
													'subtitle' => esc_html__( 'Accepted values, limits, or format notes for this parameter.', 'eazydocs' ),
													'default'  => '',
												),
											),
										),
									),
								),
								array(
									'title'  => esc_html__( 'Request', 'eazydocs' ),
									'fields' => array(
										array(
											'id'       => 'request_content_type',
											'type'     => 'select',
											'title'    => esc_html__( 'Content Type', 'eazydocs' ),
											'subtitle' => esc_html__( 'Media type of the request body. Use JSON when the endpoint has no body.', 'eazydocs' ),
											'options'  => array(
												'application/json'                  => 'application/json',
												'multipart/form-data'               => 'multipart/form-data',
												'application/x-www-form-urlencoded' => 'application/x-www-form-urlencoded',
												'text/plain'                        => 'text/plain',
												'application/xml'                   => 'application/xml',
											),
											'default'  => 'application/json',
										),
										array(
											'id'           => 'request_headers',
											'type'         => 'group',
											'title'        => esc_html__( 'Request Headers', 'eazydocs' ),
											'subtitle'     => esc_html__( 'Extra request headers besides authentication, such as Idempotency-Key.', 'eazydocs' ),
											'button_title' => esc_html__( 'Add Header', 'eazydocs' ),
											'default'      => array(),
											'fields'       => array(
												array(
													'id'          => 'name',
													'type'        => 'text',
													'title'       => esc_html__( 'Header Name', 'eazydocs' ),
													'subtitle'    => esc_html__( 'HTTP header name sent with the request.', 'eazydocs' ),
													'placeholder' => 'Content-Type',
													'default'     => '',
												),
												array(
													'id'          => 'value',
													'type'        => 'text',
													'title'       => esc_html__( 'Example Value', 'eazydocs' ),
													'subtitle'    => esc_html__( 'Sample value shown in the request headers table.', 'eazydocs' ),
													'placeholder' => 'application/json',
													'default'     => '',
												),
												array(
													'id'       => 'description',
													'type'     => 'text',
													'title'    => esc_html__( 'Description', 'eazydocs' ),
													'subtitle' => esc_html__( 'When readers should send this header.', 'eazydocs' ),
													'default'  => '',
												),
											),
										),
										array(
											'id'       => 'request_body',
											'type'     => 'textarea',
											'title'    => esc_html__( 'Request Body', 'eazydocs' ),
											'subtitle' => esc_html__( 'Describe the request payload. Leave empty for GET or when there is no body.', 'eazydocs' ),
											'default'  => '',
										),
										array(
											'id'       => 'request_example',
											'type'     => 'code_editor',
											'title'    => esc_html__( 'Request Example', 'eazydocs' ),
											'subtitle' => esc_html__( 'Sample payload shown in the Implementation panel on the public page.', 'eazydocs' ),
											'default'  => '',
											'settings' => array(
												'theme' => 'default',
												'mode'  => 'javascript',
											),
										),
									),
								),
								array(
									'title'  => esc_html__( 'Responses', 'eazydocs' ),
									'fields' => array(
										array(
											'id'                     => 'responses',
											'type'                   => 'group',
											'title'                  => esc_html__( 'Responses', 'eazydocs' ),
											'subtitle'               => esc_html__( 'Document each status code you want readers to handle, including success and common errors.', 'eazydocs' ),
											'button_title'           => esc_html__( 'Add Response', 'eazydocs' ),
											'accordion_title_number' => true,
											'accordion_title_by'     => array( 'status', 'description' ),
											'default'                => array(),
											'fields'                 => array(
												array(
													'id'       => 'status',
													'type'     => 'number',
													'title'    => esc_html__( 'Status Code', 'eazydocs' ),
													'subtitle' => esc_html__( 'HTTP status returned for this response.', 'eazydocs' ),
													'default'  => 200,
												),
												array(
													'id'          => 'description',
													'type'        => 'text',
													'title'       => esc_html__( 'Summary', 'eazydocs' ),
													'subtitle'    => esc_html__( 'Short label shown beside the status code, such as OK or Not found.', 'eazydocs' ),
													'placeholder' => esc_html__( 'OK', 'eazydocs' ),
													'default'     => '',
												),
												array(
													'id'       => 'content_type',
													'type'     => 'select',
													'title'    => esc_html__( 'Content Type', 'eazydocs' ),
													'subtitle' => esc_html__( 'Media type of the response body.', 'eazydocs' ),
													'options'  => array(
														'application/json'                  => 'application/json',
														'multipart/form-data'               => 'multipart/form-data',
														'application/x-www-form-urlencoded' => 'application/x-www-form-urlencoded',
														'text/plain'                        => 'text/plain',
														'application/xml'                   => 'application/xml',
													),
													'default'  => 'application/json',
												),
												array(
													'id'           => 'headers',
													'type'         => 'group',
													'title'        => esc_html__( 'Response Headers', 'eazydocs' ),
													'subtitle'     => esc_html__( 'Optional response headers worth documenting, such as X-Request-Id.', 'eazydocs' ),
													'button_title' => esc_html__( 'Add Header', 'eazydocs' ),
													'default'      => array(),
													'fields'       => array(
														array(
															'id'          => 'name',
															'type'        => 'text',
															'title'       => esc_html__( 'Header Name', 'eazydocs' ),
															'subtitle'    => esc_html__( 'HTTP header name returned with this response.', 'eazydocs' ),
															'placeholder' => 'X-Request-Id',
															'default'     => '',
														),
														array(
															'id'       => 'description',
															'type'     => 'text',
															'title'    => esc_html__( 'Description', 'eazydocs' ),
															'subtitle' => esc_html__( 'What this header tells the client.', 'eazydocs' ),
															'default'  => '',
														),
													),
												),
												array(
													'id'       => 'body',
													'type'     => 'textarea',
													'title'    => esc_html__( 'Response Body', 'eazydocs' ),
													'subtitle' => esc_html__( 'Describe the response payload structure.', 'eazydocs' ),
													'default'  => '',
												),
												array(
													'id'       => 'example',
													'type'     => 'code_editor',
													'title'    => esc_html__( 'Response Example', 'eazydocs' ),
													'subtitle' => esc_html__( 'Sample JSON shown in the Implementation panel on the public page.', 'eazydocs' ),
													'default'  => '',
													'settings' => array(
														'theme' => 'default',
														'mode'  => 'javascript',
													),
												),
											),
										),
									),
								),
								array(
									'title'  => esc_html__( 'Examples', 'eazydocs' ),
									'fields' => array(
										array(
											'id'                 => 'examples',
											'type'               => 'group',
											'title'              => esc_html__( 'Code Examples', 'eazydocs' ),
											'subtitle'           => esc_html__( 'Copy-ready snippets for cURL, JavaScript, and PHP. The first tab is set under Settings.', 'eazydocs' ),
											'button_title'       => esc_html__( 'Add Example', 'eazydocs' ),
											'accordion_title_by' => array( 'language' ),
											'default'            => array(),
											'fields'             => array(
												array(
													'id'       => 'language',
													'type'     => 'select',
													'title'    => esc_html__( 'Language', 'eazydocs' ),
													'subtitle' => esc_html__( 'Language tab shown in the Implementation panel.', 'eazydocs' ),
													'options'  => array(
														'curl'       => 'cURL',
														'javascript' => 'JavaScript',
														'php'        => 'PHP',
													),
													'default'  => 'curl',
												),
												array(
													'id'          => 'label',
													'type'        => 'text',
													'title'       => esc_html__( 'Tab Label', 'eazydocs' ),
													'subtitle'    => esc_html__( 'Optional custom tab name. Leave blank to use the language name.', 'eazydocs' ),
													'placeholder' => 'cURL',
													'default'     => '',
												),
												array(
													'id'       => 'code',
													'type'     => 'code_editor',
													'title'    => esc_html__( 'Example Code', 'eazydocs' ),
													'subtitle' => esc_html__( 'Full snippet visitors can copy from the Implementation panel.', 'eazydocs' ),
													'default'  => '',
													'settings' => array(
														'theme' => 'default',
														'mode'  => 'javascript',
													),
												),
											),
										),
									),
								),
							),
						),
					),
				),
			),
		),
	),
) );

CSF::createSection( $meta, array(
	'id'     => 'ezd_api_settings',
	'title'  => esc_html__( 'Settings', 'eazydocs' ),
	'icon'   => 'dashicons dashicons-admin-generic',
	'fields' => array(
		array(
			'type'    => 'subheading',
			'content' => esc_html__( 'Display', 'eazydocs' ),
		),
		array(
			'type'    => 'notice',
			'style'   => 'info',
			'content' => esc_html__( 'These options change how this API Doc looks on the frontend. They do not change saved endpoint data.', 'eazydocs' ),
		),
		ezd_csf_switcher_field( array(
			'id'       => 'show_method_badges',
			'title'    => esc_html__( 'Method Badges', 'eazydocs' ),
			'subtitle' => esc_html__( 'Show GET, POST, and other method badges in the left navigation and beside each path.', 'eazydocs' ),
			'default'  => true,
			'class'    => 'eazydocs-promax-notice',
		) ),
		ezd_csf_switcher_field( array(
			'id'       => 'show_try_it_placeholder',
			'title'    => esc_html__( 'Implementation Panel', 'eazydocs' ),
			'subtitle' => esc_html__( 'Show the right-hand code panel. This is documentation only and does not call the live API.', 'eazydocs' ),
			'default'  => true,
			'class'    => 'eazydocs-promax-notice',
		) ),
		array(
			'id'       => 'default_example_language',
			'type'     => 'select',
			'title'    => esc_html__( 'Default Language', 'eazydocs' ),
			'subtitle' => esc_html__( 'Language tab selected first. Visitors can still switch between cURL, JavaScript, and PHP.', 'eazydocs' ),
			'options'  => array(
				'curl'       => 'cURL',
				'javascript' => 'JavaScript',
				'php'        => 'PHP',
			),
			'default'  => 'curl',
			'chosen'   => true,
			'class'    => 'eazydocs-promax-notice',
		),
	),
) );
